### PR TITLE
latex: fix latex rendering

### PR DESCRIPTION
**Pull request by oharboe**
Latex needs PDF files and netlistsvg renders svg files, convert to PDF files using inkscape.

Also fix render_diagram() so it works from latex as well.

### CODE REVIEW

**Comment by oharboe** [comment]
@mithro There seems to be a problem with yosys dependencies in CI.

**Comment by mithro** [comment]
I think we need to change the channel in `environment.yml` from `symbiflow` to `LiteX-Hub` (which https://github.com/hdl/conda-eda pushes too).

**Comment by mithro** [comment]
Testing in https://github.com/SymbiFlow/sphinxcontrib-hdl-diagrams/pull/84

**Comment by mithro** [comment]
Looks like there is also #85

**Comment by oharboe** [comment]
> Looks like there is also #85

Thanks for looking into the build failures. I suppose that has to be fixed before proceeding with this PR.

**Comment by oharboe** [comment]
Once the CI is working and a latex test case is added, I want to look into if https://www.sphinx-doc.org/en/master/usage/extensions/imgconverter.html can be used.

I think the solution is then to simply generate .svg images and leave the rest to https://www.sphinx-doc.org/en/master/usage/extensions/imgconverter.html.

However I do have https://www.sphinx-doc.org/en/master/usage/extensions/imgconverter.html enabled, yet I got the error that prompted me to add the svg to pdf conversion in this PR.

**Comment by mithro** [comment]
If you rebase I think the readthedocs build should go green?

**Comment by mithro** [comment]
Looks like that worked.

**Comment by oharboe** [comment]
@mithro Thanks!

**Pull request merged**
