### PR TITLE
tests: run html and latexpdf builders for all tests

### PR DESCRIPTION
**Pull request by oharboe**
These two builders are substantially different, so worth running both.

Other builders, such as DirectoryHTMLBuilder, doesn't result in different codepaths for wavedrom graphics

### CODE REVIEW

**Comment by oharboe** [comment]
graphicsmagick-imagemagick-compat might be a better dependency than inkscape, but let's see if this passes tests now that I added inkscape as a dependency first.

```
$ apt-file search /usr/bin/convert | grep -w convert
graphicsmagick-imagemagick-compat: /usr/bin/convert
```

**Comment by mithro** [comment]
Doesn't appear that inkscape is available via direct conda channels, might need to add `conda-forge` as a channel?

**Comment by oharboe** [comment]
> graphicsmagick-imagemagick-compat

How about switching to "convert" from the Ubuntu graphicsmagick-imagemagick-compat package?

[sphinx.ext.imgconverter](https://www.sphinx-doc.org/en/master/usage/extensions/imgconverter.html) relies on "convert", so perhaps a more suitable dependency?

If "convert" exists, I can make change from inkscape to convert...

**Comment by mithro** [comment]
If `convert` works for `svg` files, then go ahead.

**Comment by mithro** [comment]
The CI looks like it is failing because no `pdf` file was created?

**Comment by oharboe** [comment]
> The CI looks like it is failing because no `pdf` file was created?

Using "convert" comes with it's own problems...

$ convert ./docs/fpga-microarchitecture/structural-schematics/ce.svg foo.pdf
convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/426.

**Comment by oharboe** [comment]
@mithro The failure is actually in yosys, which is odd... see assert in line 300. This PR doesn't modify that part of the code. Strange...

yowasp_yosys.run_yosys() returns an error code that is not checked....



https://github.com/YoWASP/yosys/blob/3767b1d481cd1197211dbdc6e509c4748104dba0/pypi/yowasp_yosys/__init__.py#L11C27-L11C35

https://github.com/YoWASP/runtime/blob/2d89db49c29a382a6801a45b09e36516c71d32b3/yowasp_runtime/__init__.py#L18


```
writing... Running YoWASP yosys: ['-q', '-p', 'prep -top ADDER ; cd ADDER; script /home/runner/work/sphinxcontrib-hdl-diagrams/sphinxcontrib-hdl-diagrams/tests/build/TestYosysScript/test_yosys_script/yosys_script.ys; show -format pdf -prefix /home/runner/work/sphinxcontrib-hdl-diagrams/sphinxcontrib-hdl-diagrams/tests/build/TestYosysScript/test_yosys_script/build/test_yosys_script-35-build-TestYosysScript-test_yosys_script-adder', '/home/runner/work/sphinxcontrib-hdl-diagrams/sphinxcontrib-hdl-diagrams/tests/build/TestYosysScript/test_yosys_script/adder.v']
failed
```

image

**Comment by oharboe** [comment]
@mithro Tested locally, but it seems like it runs out of memory... I am not surprised latex needs substantially more memory than the html output...

image

**Comment by mithro** [comment]
Overall, this change looks fine.

From what I can see, this doesn't change the memory usage?

I tried adding the following;
```patch
diff --git a/conda.mk b/conda.mk
index cf35d8b..6c60817 100644
--- a/conda.mk
+++ b/conda.mk
@@ -142,7 +142,7 @@ $(CONDA_ENVS_DIR): $(CONDA_PYTHON)
        $(MKDIR) "$(CONDA_ENVS_DIR)"
 
 $(CONDA_ENV_PYTHON): $(ENVIRONMENT_FILE) $(REQUIREMENTS_FILE) | $(CONDA_PYTHON) $(CONDA_PKGS_DEP) $(CONDA_ENVS_DIR) $(CONDA_PYVENV)
-       $(IN_CONDA_ENV_BASE) conda env update --name $(CONDA_ENV_NAME) --file $(ENVIRONMENT_FILE)
+       $(IN_CONDA_ENV_BASE) /usr/bin/time --verbose conda env update --name $(CONDA_ENV_NAME) --file $(ENVIRONMENT_FILE)
        $(TOUCH) "$(CONDA_ENV_PYTHON)"
 
 env:: $(CONDA_ENV_PYTHON)
```

Before - `Maximum resident set size (kbytes): 3493760`
After - `Maximum resident set size (kbytes): 3305444`

**Comment by oharboe** [comment]
@mithro The extra memory consumption is not surprising: I think it comes from testing latex in addition to html...

**Comment by oharboe** [comment]
@mithro I cant test anything more until Monday... I am unsure on what to try next...

**Comment by mithro** [comment]
From my reading of the output, the command seems to be failing during the conda environment setup before anything like tests are run.

**Comment by mithro** [comment]
I'm going to proceed with merging.

**Comment by oharboe** [comment]
> I'm going to proceed with merging.

Thanks!

It would be great to have the regression test working.

I think rsvg-r is the least problematic depdendency. inkscape and convert are tools on top of a raft of libraries and rsvg-r seems like a small leaf dependency.

**Pull request merged**
